//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_NMCNPM_SE.G19_QLNSNhaNam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbQuanlyBanHangNhaSachNhaNamEntities1 : DbContext
    {
        public dbQuanlyBanHangNhaSachNhaNamEntities1()
            : base("name=dbQuanlyBanHangNhaSachNhaNamEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChiTietHD> tblChiTietHDs { get; set; }
        public virtual DbSet<tblChiTietNhap> tblChiTietNhaps { get; set; }
        public virtual DbSet<tblHoaDon> tblHoaDons { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblNhap> tblNhaps { get; set; }
        public virtual DbSet<tblSach> tblSaches { get; set; }
        public virtual DbSet<tblTaiKhoan> tblTaiKhoans { get; set; }
        public virtual DbSet<View_XemChiTietNhap> View_XemChiTietNhap { get; set; }
        public virtual DbSet<View_XemDanhSachHoaDon> View_XemDanhSachHoaDon { get; set; }
        public virtual DbSet<View_XemDanhSachNhanVien> View_XemDanhSachNhanVien { get; set; }
        public virtual DbSet<View_XemDanhSachPhieuNhap> View_XemDanhSachPhieuNhap { get; set; }
        public virtual DbSet<View_XemDanhSachSach> View_XemDanhSachSach { get; set; }
        public virtual DbSet<viewNVPW> viewNVPWs { get; set; }
        public virtual DbSet<vwNhanvienHoadonChitietHD> vwNhanvienHoadonChitietHDs { get; set; }
    }
}
