//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_NMCNPM_SE.G19_QLNSNhaNam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietNhap
    {
        public string MaPN { get; set; }
        public string Masach { get; set; }
        public Nullable<int> iSoluong { get; set; }
        public Nullable<double> fDongia { get; set; }
        public Nullable<double> fThanhtien { get; set; }
    
        public virtual tblNhap tblNhap { get; set; }
        public virtual tblSach tblSach { get; set; }
    }
}
