//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_NMCNPM_SE.G19_QLNSNhaNam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhap()
        {
            this.tblChiTietNhaps = new HashSet<tblChiTietNhap>();
        }
    
        public string MaPN { get; set; }
        public string sMaNV { get; set; }
        public Nullable<System.DateTime> dNgaylap { get; set; }
        public Nullable<bool> bLoai { get; set; }
        public Nullable<double> fTongGT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietNhap> tblChiTietNhaps { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
