//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_NMCNPM_SE.G19_QLNSNhaNam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblTaiKhoan
    {
        [Required(ErrorMessage = "Username field is required")]
        public string sMaNV { get; set; }
        [Required(ErrorMessage = "Password field is required")]
        public string sMatkhau { get; set; }

        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
