//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_NMCNPM_SE.G19_QLNSNhaNam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_XemDanhSachNhanVien
    {
        public string sMaNV { get; set; }
        public string sTenNV { get; set; }
        public Nullable<System.DateTime> dNgaysinh { get; set; }
        public Nullable<bool> bGioitinh { get; set; }
        public string sDiachi { get; set; }
        public Nullable<System.DateTime> dNgayvaolam { get; set; }
        public string sSĐT { get; set; }
        public Nullable<double> fLuong { get; set; }
        public Nullable<bool> bVaitro { get; set; }
        public Nullable<bool> bTrangthai { get; set; }
        public string sCCCD { get; set; }
    }
}
