//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_NMCNPM_SE.G19_QLNSNhaNam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_XemDanhSachHoaDon
    {
        public string sMaHD { get; set; }
        public string sMaNV { get; set; }
        public Nullable<System.DateTime> dNgaylap { get; set; }
        public Nullable<double> fTongHD { get; set; }
    }
}
